Some changes

diff --git a/usr/share/system-setup-tools/system-setup-jabber b/usr/share/system-setup-tools/system-setup-jabber
--- a/usr/share/system-setup-tools/system-setup-jabber
+++ b/usr/share/system-setup-tools/system-setup-jabber
@@ -58,7 +58,23 @@ if ! [ "$required_packages" = "" ]; then
 fi
 
 # Discovery system configuration
-DOMAINNAME=`hostname`
+HOSTNAME=`hostname`
+
+# Ask for hostname
+while [ "${DOMAINNAME}" = "" ]; do
+    $color_Cyan
+    echo -n "Enter your hostname [${HOSTNAME}]: "; read DOMAINNAME
+    $color_Off
+    if [ "${DOMAINNAME}" = "" ]; then
+	DOMAINNAME="${HOSTNAME}"
+    fi
+    if ! ping ${DOMAINNAME} -c1 >/dev/null 2>&1; then
+	$color_Red
+	echo "Error while resolving host ${DOMAINNAME}!. Please choose another one, or fix DNS configuration settings!"
+	$color_Off
+	DOMAINNAME=""
+    fi
+done
 
 # Check, if /etc/hosts file already exists, then backup it
 if [ -f /etc/hosts ]; then
@@ -67,8 +83,7 @@ fi
 
 # Create new hosts file
 cat > /etc/hosts << EOF
-127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 ${DOMAINNAME}
-::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
+127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 ${HOSTNAME} ${DOMAINNAME}
 EOF
 
 # Check, if ejabberd configuration file already exists, then backup it
diff --git a/usr/share/system-setup-tools/system-setup-postfix b/usr/share/system-setup-tools/system-setup-postfix
--- a/usr/share/system-setup-tools/system-setup-postfix
+++ b/usr/share/system-setup-tools/system-setup-postfix
@@ -58,9 +58,24 @@ if ! [ "$required_packages" = "" ]; then
     fi
 fi
 
-
 # Discovery system configuration
-DOMAINNAME=`hostname`
+HOSTNAME=`hostname`
+
+# Ask for hostname
+while [ "${DOMAINNAME}" = "" ]; do
+    $color_Cyan
+    echo -n "Enter your hostname [${HOSTNAME}]: "; read DOMAINNAME
+    $color_Off
+    if [ "${DOMAINNAME}" = "" ]; then
+	DOMAINNAME="${HOSTNAME}"
+    fi
+    if ! ping ${DOMAINNAME} -c1 >/dev/null 2>&1; then
+	$color_Red
+	echo "Error while resolving host ${DOMAINNAME}!. Please choose another one, or fix DNS configuration settings!"
+	$color_Off
+	DOMAINNAME=""
+    fi
+done
 
 # Check, if main.cf file already exists, then backup it
 if [ -f /etc/postfix/main.cf ]; then
