work on system-setup-dhcpd

diff --git a/usr/share/system-setup-tools/system-setup-autologin b/usr/share/system-setup-tools/system-setup-autologin
--- a/usr/share/system-setup-tools/system-setup-autologin
+++ b/usr/share/system-setup-tools/system-setup-autologin
@@ -21,22 +21,14 @@ if ! [ "$(whoami)" = "root" ]; then
     exit 1
 fi
 
-# MDM custom.conf variable
-mdm_custom="/etc/mdm/custom.conf"
+# kdmrc file
+kdmrc_file="/etc/kde/kdm/kdmrc"
 
 # Check which display manager in use
-if ! [ -f ${mdm_custom} ]; then
-    echo "MDM display manager is not found."
+if ! [ -f ${kdmrc_file} ]; then
+    echo "KDM display manager is not found."
     echo "Exiting..."
     exit 0
-else
-    [ -f /etc/sysconfig/desktop ] && . /etc/sysconfig/desktop
-    if ! [ "$DISPLAYMANAGER" = "/usr/sbin/mdm" ]; then
-	echo "MDM desktop installed, but not in use."
-	echo "Please switch to MDM display manager, and run me again."
-	echo "Exiting..."
-	exit 0
-    fi
 fi
 
 # Get the user arguments
diff --git a/usr/share/system-setup-tools/system-setup-dhcpd b/usr/share/system-setup-tools/system-setup-dhcpd
--- a/usr/share/system-setup-tools/system-setup-dhcpd
+++ b/usr/share/system-setup-tools/system-setup-dhcpd
@@ -34,7 +34,7 @@ if ! [ -f /var/lib/system-setup-tools/named ]; then
 fi
 
 # Install required packages
-pk="dhcp"
+pk="dhcp bind"
 for i in $pk; do
 	if ! rpm -q $i >/dev/null 2>&1; then
 		required_packages="$required_packages $i"
@@ -62,7 +62,7 @@ fi
 # Ask for network device
 while [ "${IFACE}" = "" ]; do
     case ${system_ver} in
-	17)
+	17|18)
 	    FOUND_IFACE=`ifconfig -a | sed 's/[: ].*//;/^\(lo\|\)$/d' | head -1`
 	    ;;
 	*)
@@ -75,17 +75,19 @@ while [ "${IFACE}" = "" ]; do
     if [ "${IFACE}" = "" ]; then
 	IFACE="${FOUND_IFACE}"
     fi
-    if ! ifconfig ${IFACE} >/dev/null 2>&1; then
+    if ! ip addr show ${IFACE} >/dev/null 2>&1; then
 	$color_Red
 	echo "Error fetching network device: ${IFACE}"
 	$color_Off
 	IFACE=""
     fi
-    if ifconfig ${IFACE} | head -2 | tail -1 | grep "BROADCAST" >/dev/null 2>&1; then
-	$color_Red
-	echo "Error fetching IP address for device: ${IFACE}"
-	$color_Off
-	IFACE=""
+    if ! [ -z ${IFACE} ]; then
+	if ! ip addr show ${IFACE} | grep "inet " >/dev/null 2>&1; then
+	    $color_Red
+	    echo "Error fetching IP address for device: ${IFACE}"
+	    $color_Off
+	    IFACE=""
+	fi
     fi
 done
 
@@ -155,6 +157,13 @@ subnet $NETWORK netmask $NETMASK {
     }
 }
 EOF
+
+# Generate new rndc key if not found
+if ! [ -f /etc/rndc.key ]; then
+    echo "Generating /etc/rndc.key"
+    rndc-confgen -ac /etc/rndc.key
+    chown named:named /etc/rndc.key
+fi
 
 # Enable dhcp daemon
 chkconfig dhcpd on
